[package]
name = "smol-experiment"
version = "0.1.0"
authors = ["Hiroaki Nakamura <hnakamur@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smol = "0.4.3"
num_cpus = "1.13.0"

[patch.crates-io]
smol = { path = "../../../github.com/stjepang/smol" }
